import type { TopicContent } from '../../data/types';

export const content: TopicContent = {
  domainId: 'd7',
  topicId: 'd7-t8',
  overview: `Patch and vulnerability management is the ongoing operational discipline of finding, prioritizing, and fixing weaknesses in systems before attackers exploit them. Vulnerability management is the broader cycle — discover assets, scan for weaknesses, assess and prioritize by risk, remediate or mitigate, and verify — while patch management is the specific, recurring process of acquiring, testing, and deploying vendor updates. Both depend on an accurate asset inventory: you cannot scan or patch systems you do not know exist, which is why this topic connects tightly to configuration and asset management.

Vulnerability scanning is the core discovery activity. Scans can be unauthenticated (viewing the system as an external attacker would, from the outside) or authenticated/credentialed (logging in to inspect installed software and configuration in depth); credentialed scans are more accurate and produce fewer false positives. Scanning identifies missing patches, insecure configurations, and known CVEs, typically scored with CVSS to indicate technical severity. Importantly, CVSS severity alone is not the same as organizational risk — prioritization must weigh exploitability (is it being actively exploited in the wild?), asset criticality and exposure (internet-facing vs. internal), and business impact. This risk-based prioritization is what separates mature programs from those that simply chase the highest CVSS numbers.

Patch management follows a disciplined cycle: obtain the patch, test it in a non-production environment to catch instability and regressions, deploy it through the change-management process (with a maintenance window and a rollback plan), and verify that it applied and remediated the vulnerability. Rushing untested patches straight to production can cause outages, while indefinitely delaying critical patches leaves exploitable exposure — the exam wants you to balance stability with timely risk reduction, deploying critical/actively-exploited fixes fastest, often via an emergency change. Where a patch is unavailable or cannot be applied immediately, compensating mitigations (virtual patching via IPS, network isolation, disabling the vulnerable feature) reduce risk in the interim. The cycle is continuous, not a one-time project, and metrics such as mean time to remediate track its effectiveness.`,
  examFraming: `(ISC)² frames this topic around risk-based prioritization and disciplined deployment. The recurring lesson: patch the most dangerous, most exposed, actively-exploited vulnerabilities first — technical CVSS severity informs but does not equal business risk, which also considers exploitability, exposure, and asset criticality. Expect scenarios where you must choose between rushing an untested patch (risking outage) and patching through proper testing and change control; the balanced answer is to test and deploy via change management, escalating truly critical or actively-exploited flaws to an emergency change. Know that credentialed/authenticated scans are more accurate than unauthenticated ones, and that an accurate asset inventory is a prerequisite for scanning and patching. When a patch cannot be applied yet, recognize compensating mitigations (virtual patching/IPS, isolation, disabling the feature) as valid interim risk reduction. Treat vulnerability management as a continuous cycle, and don't confuse finding a vulnerability (scanning) with fixing it (remediation).`,
  keyTerms: [
    { term: 'Vulnerability Management', definition: 'The continuous cycle of discovering assets, scanning for weaknesses, assessing and prioritizing by risk, remediating, and verifying.' },
    { term: 'Patch Management', definition: 'The recurring process of acquiring, testing, deploying, and verifying vendor updates that fix vulnerabilities or defects.' },
    { term: 'Authenticated (Credentialed) Scan', definition: 'A scan that logs into the target to inspect installed software and configuration in depth, yielding higher accuracy and fewer false positives.' },
    { term: 'Unauthenticated Scan', definition: 'A scan performed without credentials that sees a system as an external attacker would, useful for external exposure but less thorough.' },
    { term: 'CVSS (Common Vulnerability Scoring System)', definition: 'A standardized score of a vulnerability’s technical severity; it informs but does not by itself equal organizational risk.' },
    { term: 'Risk-Based Prioritization', definition: 'Ranking remediation by combining technical severity with exploitability, asset criticality, and exposure rather than by CVSS score alone.' },
    { term: 'Virtual Patching', definition: 'Using a control such as an IPS or WAF to block exploitation of a vulnerability when a real patch cannot yet be applied.' },
    { term: 'Zero-Day', definition: 'A vulnerability that is exploited before a vendor patch is available, requiring compensating mitigations until a fix exists.' },
  ],
  scenario: `A quarterly scan returns hundreds of findings across the enterprise. Two stand out: a CVSS 9.8 flaw in an internal reporting tool reachable only from a small admin subnet, and a CVSS 7.5 flaw in the internet-facing customer portal that threat intelligence reports is being actively exploited in the wild. The infrastructure team's instinct is to patch strictly by CVSS score, starting with the 9.8.

Risk-based prioritization suggests otherwise. Although the internal flaw has a higher CVSS, it is exposed only to a trusted, restricted subnet, whereas the internet-facing portal flaw is actively exploited and directly reachable by attackers — making it the greater real-world risk despite its lower score. The portal fix should be prioritized, likely as an emergency change, ideally after a quick test, with a rollback plan; if the patch cannot be applied immediately, virtual patching via the WAF/IPS or temporary isolation reduces exposure in the interim. Meanwhile, credentialed scanning would improve accuracy for the next cycle, and an accurate asset inventory ensures no exposed system is missed. A CISSP question here tests whether you prioritize by actual risk (exploitability plus exposure plus criticality), not by CVSS number alone, and whether you balance timely remediation with testing and change control.`,
  examTraps: [
    `CVSS severity is not the same as organizational risk — prioritize using exploitability (active exploitation), exposure (internet-facing vs. internal), and asset criticality, not the raw score alone.`,
    `Do not push untested patches straight to production (risking outages), but do not indefinitely delay critical/actively-exploited patches either — test and deploy via change management, escalating truly critical fixes to an emergency change.`,
    `Credentialed/authenticated scans are more accurate and yield fewer false positives than unauthenticated scans; if results look thin or noisy, credentials may be the issue.`,
    `You cannot scan or patch what you do not know you have — an accurate asset inventory is a prerequisite, not an afterthought.`,
    `Finding a vulnerability (scanning) is not the same as fixing it (remediation); a scan report with no remediation and verification does not reduce risk.`,
  ],
  resources: [
    { label: 'Vulnerability management lifecycle and CVSS (CISSP)', url: 'https://www.youtube.com/results?search_query=cissp+vulnerability+management+lifecycle+cvss' },
    { label: 'Risk-based patch prioritization and credentialed scans', url: 'https://www.youtube.com/results?search_query=cissp+risk+based+patch+management+credentialed+scan' },
  ],
};
